# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            TiDB Weekly
tagline:          'TiDB Weekly'
description:      'Inspired by Google Spanner/F1, PingCAP develops TiDB, an open source distributed Hybrid Transactional/Analytical Processing (HTAP) database.'
url:              http://weekly.pingcap.com
siteurl:          https://www.pingcap.com
baseurl:          ""
excerpt_separator: "<!--more-->"

author:
  name:           'PingCAP'
  url:            https://www.pingcap.com

paginate:         5

# Custom vars
version:          Beta20160730

github:
  repo:           https://github.com/pingcap/tidb

blog:
  url:            https://pingcap.github.io/blog

